异常处理常见手段： try catch finally throws
============================================================================================================

一：try catch

将可能抛出FileNotFoundException 文件不存在异常的代码放在try里
如果文件存在，就会顺序往下执行，并且不执行catch块中的代码
如果文件不存在，try 里的代码会立即终止，程序流程会运行到对应的catch块中e.printStackTrace(); 会打印出方法的调用痕迹，
如此例，会打印出异常开始于TestException的位置，这样就便于定位和分析到底哪里出了异常

package exception;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class TestException {
 
    public static void main(String[] args) {
         
        File f= new File("d:/LOL.exe");
         
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
        catch(FileNotFoundException e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
         
    }
}


二：使用异常的父类进行catch

FileNotFoundException是Exception的子类，使用Exception也可以catch住FileNotFoundException

package exception;
  
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class TestException {
  
    public static void main(String[] args) {
          
        File f= new File("d:/LOL.exe");
          
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
         
        catch(Exception e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
          
    }
}


三：多异常捕捉方法

有的时候一段代码会抛出多种异常，比如

new FileInputStream(f);
Date d = sdf.parse("2016-06-03");

这段代码，会抛出 文件不存在异常 FileNotFoundException 和 解析异常ParseException

}

1、多异常捕捉办法一：

解决办法之一是分别进行catch
 
catch (FileNotFoundException e) {
    System.out.println("d:/LOL.exe不存在");
    e.printStackTrace();
} catch (ParseException e) {
    System.out.println("日期格式解析错误");
    e.printStackTrace();
}

2、多异常捕捉办法二：

另一个种办法是把多个异常，放在一个catch里统一捕捉
 
这种方式从 JDK7开始支持，好处是捕捉的代码更紧凑，不足之处是，一旦发生异常，不能确定到底是哪种异常，需要通过instanceof 进行判断具体的异常类型
 catch (FileNotFoundException | ParseException e) {
    if (e instanceof FileNotFoundException)
	    System.out.println("d:/LOL.exe不存在");
    if (e instanceof ParseException)
	    System.out.println("日期格式解析错误");
 }


四、finally

无论是否出现异常，finally中的代码都会被执行

package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class TestException {
 
    public static void main(String[] args) {
         
        File f= new File("d:/LOL.exe");
         
        try{
            System.out.println("试图打开 d:/LOL.exe");
            new FileInputStream(f);
            System.out.println("成功打开");
        }
        catch(FileNotFoundException e){
            System.out.println("d:/LOL.exe不存在");
            e.printStackTrace();
        }
        finally{
            System.out.println("无论文件是否存在， 都会执行的代码");
        }
    }
}


五、throws

考虑如下情况：
主方法调用method1
method1调用method2
method2中打开文件

method2中需要进行异常处理
但是method2不打算处理，而是把这个异常通过throws抛出去
那么method1就会接到该异常。 处理办法也是两种，要么是try catch处理掉，要么也是抛出去。
method1选择本地try catch住 一旦try catch住了，就相当于把这个异常消化掉了，主方法在调用method1的时候，就不需要进行异常处理了

package exception;
 
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
 
public class TestException {
 
    public static void main(String[] args) {
        method1();
    }
 
    private static void method1() {
        try {
            method2();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
 
    private static void method2() throws FileNotFoundException {
 
        File f = new File("d:/LOL.exe");
 
        System.out.println("试图打开 d:/LOL.exe");
        new FileInputStream(f);
        System.out.println("成功打开");
 
    }
}

六、throw和throws的区别

throws与throw这两个关键字接近，不过意义不一样，有如下区别：

区别1：

throws:
跟在方法声明后面，后面跟的是异常类名
throw:
用在方法体内，后面跟的是异常类对象名   

例：
public static void method() throws ArithmeticException {// 跟在方法声明后面，后面跟的是异常类名
    int a=10;
    int b=0;
    if(b==0) {
        throw new ArithmeticException();用在方法体内，后面跟的是异常类对象名 
    }else {
        System.out.println(a/b);
    }
}
}


区别2：

throws:
可以跟多个异常类名，用逗号隔开

throw:
只能抛出一个异常对象名 

区别3：

throws:
     表示抛出异常，由该方法的调用者来处理
 
 throw:
    表示抛出异常，由该方法体内的语句来处理

区别4：

throws:
     throws表示有出现异常的可能性，并不一定出现这些异常
 
 throw:
    throw则是抛出了异常，执行throw一定出现了某种异常